# Generated by Django 4.2.20 on 2025-09-06 07:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('support', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='faqs',
            options={'verbose_name_plural': 'Faqs'},
        ),
    ]
