# Generated by Django 4.2.20 on 2025-06-25 14:52

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0002_rename_reiews_reviews_alter_reviews_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='reviews',
            options={'ordering': ['rating'], 'verbose_name_plural': 'Reviews'},
        ),
        migrations.AddField(
            model_name='reviews',
            name='created_on',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='reviews',
            name='updated_on',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
