# Generated by Django 4.2.20 on 2025-06-26 08:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0003_alter_reviews_options_reviews_created_on_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='reviews',
            options={'ordering': ['-updated_on'], 'verbose_name_plural': 'Reviews'},
        ),
    ]
