# Generated by Django 4.2.20 on 2025-04-07 06:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0003_alter_product_price_alter_product_rating'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='product',
            options={'ordering': ['sku']},
        ),
        migrations.RenameField(
            model_name='product',
            old_name='brand',
            new_name='brand_category',
        ),
    ]
