# Generated by Django 4.2.20 on 2025-06-08 15:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0004_alter_product_options_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='brand_category',
            new_name='brand',
        ),
    ]
